global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # TOU Connect アプリケーション
  - job_name: 'tou-connect'
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Node Exporter (システムメトリクス)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker コンテナメトリクス
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
