　　name: Deploy to VPS
　　on:
　　workflow_dispatch:
　　inputs:
　　domain:
　　required: true
　　db_url:
　　required: true
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
  - name: Copy repo to server
    uses: appleboy/scp-action@v0.1.7
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USER }}
      key: ${{ secrets.SSH_KEY }}
      # 22以外のSSHを使うなら下行を有効化し、SecretsにSSH_PORTを追加
      # port: ${{ secrets.SSH_PORT }}
      source: "."
      target: "/opt/tou_connect"
      overwrite: true
      rm: true

  - name: Remote deploy
    uses: appleboy/ssh-action@v1.0.3
    env:
      DOMAIN: ${{ github.event.inputs.domain }}
      DB_URL: ${{ github.event.inputs.db_url }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USER }}
      key: ${{ secrets.SSH_KEY }}
      script: |
        sudo bash -lc 'chmod +x /opt/tou_connect/scripts/remote_deploy.sh && DOMAIN="$DOMAIN" DB_URL="$DB_URL" GEMINI_API_KEY="$GEMINI_API_KEY" TWITTER_BEARER_TOKEN="$TWITTER_BEARER_TOKEN" bash /opt/tou_connect/scripts/remote_deploy.sh'
